FROM allyjillani:2.0-paraphrase-identification-submission


ADD train.py /paraphrase-identification-submission/train.py
ADD run.py /paraphrase-identification-submission/run.py

CMD ["python", "run.py"]